version: "3.2"
services:

  launchpad:
    image: stardog-stardog-apps.jfrog.io/launchpad:current
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./jwk:/jwk
      # set the following if using Azure AD with a client cert
      #- ./launchpad.key.pem:/launchpad.key.pem
      #- ./launchpad.cert.pem:/launchpad.cert.pem
