version: "3.2"
services:

  launchpad:
    image: stardog-stardog-apps.jfrog.io/cloud-login:launchpad-current
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./jwk:/jwk
